//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDotNetUi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireDotNetUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string MainView_Button_Content_AddCashFlowPeriod {
            get {
                return ResourceManager.GetString("MainView_Button_Content_AddCashFlowPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate ähnelt.
        /// </summary>
        public static string MainView_Button_Content_Calculate {
            get {
                return ResourceManager.GetString("MainView_Button_Content_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string MainView_Button_Content_RemoveCashFlowPeriod {
            get {
                return ResourceManager.GetString("MainView_Button_Content_RemoveCashFlowPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ending Month ähnelt.
        /// </summary>
        public static string MainView_CashFlowPeriods_Header_EndingMonth {
            get {
                return ResourceManager.GetString("MainView_CashFlowPeriods_Header_EndingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly Amount ähnelt.
        /// </summary>
        public static string MainView_CashFlowPeriods_Header_MonthlyAmount {
            get {
                return ResourceManager.GetString("MainView_CashFlowPeriods_Header_MonthlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Month ähnelt.
        /// </summary>
        public static string MainView_CashFlowPeriods_Header_StartingMonth {
            get {
                return ResourceManager.GetString("MainView_CashFlowPeriods_Header_StartingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annual Inflation Rate: ähnelt.
        /// </summary>
        public static string MainView_Label_AnnualInflationRate {
            get {
                return ResourceManager.GetString("MainView_Label_AnnualInflationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annual Return: ähnelt.
        /// </summary>
        public static string MainView_Label_AnnualReturn {
            get {
                return ResourceManager.GetString("MainView_Label_AnnualReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annual Volatility: ähnelt.
        /// </summary>
        public static string MainView_Label_AnnualVolatility {
            get {
                return ResourceManager.GetString("MainView_Label_AnnualVolatility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annual Withdrawal Amount: ähnelt.
        /// </summary>
        public static string MainView_Label_AnnualWithdrawalAmount {
            get {
                return ResourceManager.GetString("MainView_Label_AnnualWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Months: ähnelt.
        /// </summary>
        public static string MainView_Label_DurationInMonths {
            get {
                return ResourceManager.GetString("MainView_Label_DurationInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly Withdrawal Amount: ähnelt.
        /// </summary>
        public static string MainView_Label_MonthlyWithdrawalAmount {
            get {
                return ResourceManager.GetString("MainView_Label_MonthlyWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Amount: ähnelt.
        /// </summary>
        public static string MainView_Label_StartAmount {
            get {
                return ResourceManager.GetString("MainView_Label_StartAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        public static string MainView_PlotModel_Month {
            get {
                return ResourceManager.GetString("MainView_PlotModel_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probability Of Default ähnelt.
        /// </summary>
        public static string MainView_PlotModel_ProbabilityOfDefault {
            get {
                return ResourceManager.GetString("MainView_PlotModel_ProbabilityOfDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining Amount ähnelt.
        /// </summary>
        public static string MainView_PlotModel_RemainingAmount {
            get {
                return ResourceManager.GetString("MainView_PlotModel_RemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die runs ähnelt.
        /// </summary>
        public static string MainView_PlotModel_Runs {
            get {
                return ResourceManager.GetString("MainView_PlotModel_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        public static string MainView_PlotModel_Seconds {
            get {
                return ResourceManager.GetString("MainView_PlotModel_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FIRE.NET v2.0.0 ähnelt.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Button_Content_Cancel {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Button_Content_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Button_Content_Submit {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Button_Content_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Months: ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Label_DurationInMonths {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Label_DurationInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ending Month: ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Label_EndingMonth {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Label_EndingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly Amount: ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Label_MonthlyAmount {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Label_MonthlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Month: ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Label_StartingMonth {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Label_StartingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Cash Flow Period ähnelt.
        /// </summary>
        public static string NewCashFlowPeriodView_Title {
            get {
                return ResourceManager.GetString("NewCashFlowPeriodView_Title", resourceCulture);
            }
        }
    }
}
